### ISSUE TITLE
async batch processing API not allowing publicly-accessible image HTTP/HTTPS URL

### ISSUE THREAD

**Issue by georgeman93** [googleapis/python-vision#94]
Apparently the ImageSource attribute of vision requests should allow "A publicly-accessible image HTTP/HTTPS URL"
https://cloud.google.com/vision/docs/reference/rpc/google.cloud.vision.v1#google.cloud.vision.v1.Image
https://googleapis.dev/python/vision/latest/vision_v1/types.html

Here, the Google API core seems to only expect a google storage uri link

#### Environment details

  - OS type and version: macOS Big Sur 11.0.1
  - Python version: 3.9.1`
  - pip version: 20.3.3
  - `google-cloud-vision` version: 2.0.0

#### Code example

```python

from google.cloud import vision
client = vision.ImageAnnotatorClient()

requests = []
labels = []
# I had an array of image urls in a json file, but using the same url over and over gives the same error
images = range(100)
for img in images:
    source = {"image_uri": "https://images.unsplash.com/photo-1544845120-288673aefccc?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEyMDd9"}
    image = {"source": source}
    features = [
        {"type_": vision.Feature.Type.LABEL_DETECTION}
    ]
    requests.append({"image": image, "features": features})

# The max number of responses to output in each JSON file
batch_size = 2  # max batch size
gcs_destination = {"uri": "gs://imagesort/results/"}
output_config = {"gcs_destination": gcs_destination,
                 "batch_size": batch_size}

operation = client.async_batch_annotate_images(
    requests=requests, output_config=output_config)

print("Waiting for operation to complete...")
response = operation.result(90)
```

#### Stack trace
```
Traceback (most recent call last):
  File "/Users/georgeoconnor/imagesort/env/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Users/georgeoconnor/imagesort/env/lib/python3.9/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/georgeoconnor/imagesort/env/lib/python3.9/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Invalid gcs prefix provided in request image.source.image_uri field. Valid prefixes must start with 'gs://'."
	debug_error_string = "{"created":"@1611278568.485631000","description":"Error received from peer ipv6:[2404:6800:4015:800::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Invalid gcs prefix provided in request image.source.image_uri field. Valid prefixes must start with 'gs://'.","grpc_status":3}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/georgeoconnor/imagesort/test.py", line 22, in <module>
    operation = client.async_batch_annotate_images(
  File "/Users/georgeoconnor/imagesort/env/lib/python3.9/site-packages/google/cloud/vision_v1/services/image_annotator/client.py", line 493, in async_batch_annotate_images
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/Users/georgeoconnor/imagesort/env/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/georgeoconnor/imagesort/env/lib/python3.9/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/Users/georgeoconnor/imagesort/env/lib/python3.9/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/Users/georgeoconnor/imagesort/env/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 Invalid gcs prefix provided in request image.source.image_uri field. Valid prefixes must start with 'gs://'.

```

**Comment by munkhuushmgl** [comment]
because of security issues involved with public http/https links, we use gs bucket uri or google storage link.

I would suggest you to use local image reference.

**Comment by georgeman93** [comment]
understood, thanks
